services:
  server:
    image: ghcr.io/mgm103/go-fund-yourself-fe:latest
    container_name: go-fund-yourself-fe
    ports:
      - '3000:3000'
    environment:
      - ORIGIN=https://gofundyourself.cash
    volumes:
      - sqlite-data:/app/data

volumes:
  sqlite-data:
